name: build

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Hakoniwa-core
        run: |
          bash build.bash

      - name: Artifact Name for ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "ARTIFACT_NAME=libshakoc.so" >> $GITHUB_ENV
          echo "ARTIFACT_PATH=cmake-build/src/hakoc/libshakoc.so" >> $GITHUB_ENV

      - name: Artifact Name for mac
        if: matrix.os == 'macos-latest'
        run: |
          echo "ARTIFACT_NAME=libshakoc.dylib" >> $GITHUB_ENV
          echo "ARTIFACT_PATH=cmake-build/src/hakoc/libshakoc.dylib" >> $GITHUB_ENV

      - name: upload Artifact
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: ${{env.ARTIFACT_PATH}}

      - name: Publish archives and packages
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.ARTIFACT_PATH }}
